baseURL = 'https://kaizen.wang/'
# languageCode = "zh-CN"
defaultContentLanguage = 'zh-hans'
title = '大头的博客'
theme = "maupassant"
googleAnalytics = "UA-136328493-1"

summaryLength = 10

[author]
name = "BigHead"

[params]
author = "BigHead"
subtitle = ""
keywords = "Java,MySQL,Spring,SpringBoot,SpringCloud"
description = ""

[params.utteranc]
    enable = false
    repo = "kaizenwang/comment"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

[menu]
[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 2

[[menu.main]]
identifier = "about"
name = "关于"
url = "/about/"
weight = 3
